#!/bin/bash
source ./env

image=$(docker images --filter reference=$IMAGE_NAME -q)

if [[ -z "$image" ]]; then
    # docker build -t $IMAGE_NAME .
    docker build --no-cache -t $IMAGE_NAME .
else
    echo "Image is already built"
    echo "run vm-start"
fi
