#!/bin/bash
source ./env

docker ps -a

CONTAINER_ID=$(docker ps -a --filter name=$CONTAINER_NAME -q)
INSTANCE_RECORD=$(docker ps -a --filter name=$CONTAINER_NAME)

if [[ -z "$CONTAINER_ID" ]]; then
    echo "Container doesn't exists"
    exit 1
fi

container_status=$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME)

if [ "$container_status" = "true" ]; then
    echo "Can not destroy containr while is running"
    echo -e "\r\nStopping container..."
    echo $INSTANCE_RECORD
    docker stop $CONTAINER_ID

    echo "Retry to destroy container"
    exit 4
fi

echo -e "\r\nDestroying Container"

echo $INSTANCE_RECORD
docker rm $CONTAINER_ID
docker rmi $IMAGE_NAME

echo "Active containers:"
docker ps -a
