#!/bin/bash
source ./.env

docker ps -a

CONTAINER_ID=$(docker ps -a --filter name=$CONTAINER_NAME -q)
INSTANCE_RECORD=$(docker ps -a --filter name=$CONTAINER_NAME)

if [[ -z "$CONTAINER_ID" ]]; then
    echo "Container doesn't exists"
    exit 1
fi

echo -e "\r\nDestroying Container"

echo $INSTANCE_RECORD
docker rm $CONTAINER_ID
docker rmi $IMAGE_NAME

echo "Active containers:"
docker ps -a
