#!/bin/bash
source ./.env
set -x

mkdir -p $STORAGE_DIR


CONTAINER_ID=$(docker ps --filter name=$CONTAINER_NAME -q)
if [[ -z "$CONTAINER_ID" ]]; then
    echo "$CONTAINER_NAME container not found"
    echo "run vm-create"
    # exit 2;
fi;

echo "Creating $CONTAINER_NAME from $IMAGE_NAME"
echo $INSTANCE_RECORD

docker run --detach -it --name $CONTAINER_NAME -v $STORAGE_DIR/:$MOUNTPOINT_DIR/ $IMAGE_NAME

docker ps -a
