#!/bin/bash
source ./env

mkdir -p $STORAGE_DIR

CONTAINER_ID=$(docker ps --filter name=$CONTAINER_NAME -q)

if [[ -z "$CONTAINER_ID" ]]; then
    echo "$CONTAINER_NAME container not found"
    echo "run vm-create"
else
    echo "Creating $CONTAINER_NAME from $IMAGE_NAME"
    echo $INSTANCE_RECORD
fi;

docker run --detach -it --name $CONTAINER_NAME -v $STORAGE_DIR/:$MOUNTPOINT_DIR/ $IMAGE_NAME

docker ps -a
