#!/bin/bash

echo -e "\r\n>> Stopping container if exists"
./vm-stop
echo -e "\r\n>> destroying container if exists"
./vm-destroy
echo -e "\r\n>> Rebuilding image"
./vm-create
echo -e "\r\n>> Starting conatiner"
./vm-start
echo -e "\r\n>> Connecting to conatiner"
./vm-connect
